# Python - Exceptions

- Task 1
	- filename: [0-safe_print_list.py](./0-safe_print_list.py) 
	- function: safe prints elements in a list 

- Task 2
	- filename: [1-safe_print_integer.py](./1-safe_print_integer.py)
	- function: prints an integer with `"{:d}".format()`

- Task 3
        - filename: [2-safe_print_list_integers.py](./2-safe_print_list_integers.py)
        - function: prints the first x integers of a list

- Task 2
        - filename: []()
        - function: 
- Task 1
        - filename: []()
        - function: 

- Task 2
        - filename: []()
        - function: 
