# Python - Exceptions

- Task 0
	- filename: [0-safe_print_list.py](./0-safe_print_list.py) 
	- function: safe prints elements in a list 

- Task 1
	- filename: [1-safe_print_integer.py](./1-safe_print_integer.py)
	- function: prints an integer with `"{:d}".format()`

- Task 2
        - filename: [2-safe_print_list_integers.py](./2-safe_print_list_integers.py)
        - function: prints the first x integers of a list

- Task 3
        - filename: [3-safe_print_division.py](./3-safe_print_division.py)
        - function: function that divides 2 integers and prints the results
- Task 4
        - filename: [4-list_division.py](./4-list_division.py)
        - function: divides element by elements 2 lists

- Task 2
        - filename: []()
        - function: 
